// Vocabulário: cada termo = {c: categoria, en: termo usado no prompt, pt: nome em português,
// d: definição, u: efeito/quando usar, p: exemplo de prompt, v: "não confunda", tk: trecho para o montador,
// g: grupo do montador (quando difere da categoria), x: especificação da demo animada}
window.CATS = [
  { id: 'plano', pt: 'Planos', en: 'Shot size', q: 'Quanto do assunto cabe no quadro' },
  { id: 'angulo', pt: 'Ângulos', en: 'Camera angle', q: 'De onde a câmera olha' },
  { id: 'movimento', pt: 'Movimentos', en: 'Camera movement', q: 'Como a câmera se desloca' },
  { id: 'lente', pt: 'Lentes & foco', en: 'Lens & focus', q: 'Distância focal, abertura e foco' },
  { id: 'luz', pt: 'Luz', en: 'Lighting', q: 'Direção, dureza e cor da luz' },
  { id: 'composicao', pt: 'Composição', en: 'Composition', q: 'Onde as coisas ficam no quadro' },
  { id: 'tempo', pt: 'Tempo & ritmo', en: 'Timing', q: 'Velocidade, cadência e quadros' },
  { id: 'principios', pt: '12 princípios', en: 'Animation principles', q: 'Como o movimento parece vivo' },
  { id: 'estilo', pt: 'Estilos', en: 'Animation style', q: 'Técnica e linguagem visual' },
  { id: 'cor', pt: 'Cor & acabamento', en: 'Color & finish', q: 'Grade de cor e textura de filme' },
  { id: 'atmos', pt: 'Atmosfera', en: 'Atmosphere', q: 'Clima, partículas e ar' },
  { id: 'edicao', pt: 'Transições', en: 'Editing', q: 'Como um plano vira o outro' }
];

window.TERMS = [
// ───────────── PLANOS ─────────────
{c:'plano',en:'Extreme wide shot',pt:'Grande plano geral',x:{shot:'xws'},
 d:'O ambiente domina; o personagem ocupa uma fração mínima do quadro.',
 u:'Escala, solidão, abertura de sequência. Mostra onde estamos antes de mostrar quem.',
 p:'Extreme wide shot of a tiny explorer in a red scarf crossing a vast green valley, mountains dwarfing the figure',
 v:'No wide shot o personagem ainda é reconhecível; no extreme wide ele é quase um ponto.'},
{c:'plano',en:'Wide shot',pt:'Plano geral / de ambientação',tk:'wide establishing shot',x:{shot:'ws'},
 d:'Mostra o personagem inteiro dentro do cenário, com bastante espaço ao redor.',
 u:'Situar o espectador. Também chamado de establishing shot quando abre a cena.',
 p:'Wide establishing shot of an explorer standing in a meadow beside a small house and pine trees'},
{c:'plano',en:'Full shot',pt:'Plano inteiro',x:{shot:'fs'},
 d:'Enquadra o corpo da cabeça aos pés, com pouca folga.',
 u:'Linguagem corporal, figurino, dança, ação física.',
 p:'Full shot of the explorer from head to toe, standing still in the grass'},
{c:'plano',en:'Cowboy shot',pt:'Plano americano',tk:'medium wide cowboy shot',x:{shot:'mws'},
 d:'Do meio da coxa para cima. O nome vem dos faroestes, que precisavam mostrar o coldre.',
 u:'Postura e atitude com o rosto ainda legível. Bom para confrontos e duelos.',
 p:'Cowboy shot of the explorer, framed from mid-thigh up, confident stance'},
{c:'plano',en:'Medium shot',pt:'Plano médio',x:{shot:'ms'},
 d:'Da cintura para cima. Equilíbrio entre expressão facial e gesto das mãos.',
 u:'Plano de trabalho para ação e diálogo.',
 p:'Medium shot of the explorer from the waist up, looking toward the horizon'},
{c:'plano',en:'Medium close-up',pt:'Plano próximo',x:{shot:'mcu'},
 d:'Do peito para cima. O rosto já é o centro de atenção.',
 u:'Diálogo, entrevista, reação.',
 p:'Medium close-up of the explorer, chest up, gentle smile'},
{c:'plano',en:'Close-up',pt:'Primeiro plano',x:{shot:'cu'},
 d:'O rosto preenche o quadro.',
 u:'Emoção e intimidade. Cada microexpressão vira acontecimento.',
 p:'Close-up of the explorer\'s face, eyes reflecting the sunset',
 v:'Em inglês, close-up é o rosto; o detalhe ainda mais fechado é extreme close-up.'},
{c:'plano',en:'Extreme close-up',pt:'Primeiríssimo plano / detalhe',x:{shot:'ecu'},
 d:'Um detalhe isolado: olhos, boca, mão.',
 u:'Tensão máxima, revelação, foco absoluto.',
 p:'Extreme close-up of the explorer\'s eyes, pupils widening'},
{c:'plano',en:'Insert shot',pt:'Inserte',x:{shot:'ins'},
 d:'Plano de detalhe de um objeto que importa para a história, cortado no meio da cena.',
 u:'Mostrar uma pista, um objeto, um gesto que o plano aberto esconderia.',
 p:'Insert shot of a small red flower at the explorer\'s feet, soft morning light'},
{c:'plano',en:'Over-the-shoulder shot',pt:'Plano por cima do ombro',x:{shot:'ots'},
 d:'A câmera fica atrás do ombro de um personagem, que aparece desfocado em primeiro plano, olhando o outro.',
 u:'Diálogo com relação espacial clara entre dois personagens.',
 p:'Over-the-shoulder shot from behind a companion, focused on the explorer\'s face'},
{c:'plano',en:'Two-shot',pt:'Plano conjunto (dois)',x:{shot:'two'},
 d:'Dois personagens dividindo o quadro.',
 u:'Relação, parceria, contraste entre os dois.',
 p:'Two-shot of the explorer and a companion standing side by side'},
{c:'plano',en:'POV shot',pt:'Plano subjetivo',tk:'first-person POV shot',x:{shot:'pov'},
 d:'A câmera vê exatamente o que o personagem vê, na altura dos olhos dele.',
 u:'Imersão e identificação. Comum em jogos e terror.',
 p:'First-person POV shot walking toward a small house, hands visible at the bottom of frame'},

// ───────────── ÂNGULOS ─────────────
{c:'angulo',en:'Eye-level shot',pt:'Altura dos olhos',x:{shot:'fs',angle:'eye'},
 d:'Câmera na altura dos olhos do personagem, sem inclinação.',
 u:'Neutro, natural. O espectador é um igual.',
 p:'Eye-level shot of the explorer, neutral perspective'},
{c:'angulo',en:'Low angle',pt:'Contra-plongée',tk:'low-angle shot',x:{shot:'fs',angle:'low'},
 d:'Câmera abaixo do personagem, apontando para cima.',
 u:'Poder, heroísmo, ameaça. O personagem parece maior.',
 p:'Low-angle shot looking up at the explorer against a bright sky, heroic'},
{c:'angulo',en:'High angle',pt:'Plongée',tk:'high-angle shot',x:{shot:'fs',angle:'high'},
 d:'Câmera acima do personagem, apontando para baixo.',
 u:'Fragilidade, vulnerabilidade, vigilância.',
 p:'High-angle shot looking down at the explorer alone in the grass'},
{c:'angulo',en:'Overhead shot',pt:'Plongée absoluta / zenital',tk:'top-down overhead shot',x:{shot:'fs',angle:'overhead'},
 d:'Câmera a 90° olhando reto para baixo. Também chamado de bird\'s-eye view ou top-down.',
 u:'Padrões, mapas, coreografia. Achata a cena em desenho.',
 p:'Top-down overhead shot of the explorer lying in the grass, flat graphic composition'},
{c:'angulo',en:'Worm\'s-eye view',pt:'Contra-plongée extrema',tk:'worm\'s-eye view from ground level',x:{shot:'fs',angle:'worm'},
 d:'Câmera rente ao chão, apontando quase reto para cima.',
 u:'Monumentalidade, vertigem, estranheza.',
 p:'Worm\'s-eye view from the ground, the explorer towering above, trees reaching into the sky'},
{c:'angulo',en:'Dutch angle',pt:'Ângulo holandês',tk:'dutch angle, tilted horizon',x:{shot:'fs',angle:'dutch'},
 d:'Câmera girada no eixo da lente: o horizonte fica inclinado.',
 u:'Desconforto, instabilidade, loucura, tensão.',
 p:'Dutch angle shot of the explorer, tilted horizon, uneasy mood'},
{c:'angulo',en:'Aerial shot',pt:'Plano aéreo',x:{shot:'fs',angle:'aerial'},
 d:'Visto de muito alto, como de um drone ou helicóptero, com inclinação diagonal.',
 u:'Geografia, escala, transição entre locais.',
 p:'Aerial shot high above the valley, the explorer a small figure near the house'},

// ───────────── MOVIMENTOS ─────────────
{c:'movimento',en:'Static shot',pt:'Câmera parada',tk:'static locked-off shot',x:{shot:'ms',move:'static'},
 d:'Câmera fixa no tripé (locked-off). Só o conteúdo se move.',
 u:'Contemplação, humor seco, observação. Evita que o modelo invente movimento.',
 p:'Static locked-off shot, no camera movement, the explorer\'s scarf moving in the wind'},
{c:'movimento',en:'Pan',pt:'Panorâmica horizontal',tk:'slow pan from left to right',x:{shot:'fs',move:'pan'},
 d:'A câmera gira para os lados sobre o próprio eixo, sem sair do lugar.',
 u:'Revelar o espaço, acompanhar algo que cruza a cena.',
 p:'Slow pan from left to right across the valley, revealing the explorer',
 v:'Pan gira; truck desloca. No pan o fundo e o primeiro plano andam juntos, sem paralaxe.'},
{c:'movimento',en:'Tilt',pt:'Panorâmica vertical',tk:'slow tilt up',x:{shot:'fs',move:'tilt'},
 d:'A câmera gira para cima ou para baixo sobre o próprio eixo.',
 u:'Revelar altura, ir dos pés ao rosto, do chão ao céu.',
 p:'Slow tilt up from the explorer\'s boots to the open sky',
 v:'Tilt inclina; pedestal sobe a câmera inteira mantendo a mira reta.'},
{c:'movimento',en:'Dolly in',pt:'Travelling para frente',tk:'smooth dolly in toward the subject',x:{shot:'ms',move:'dollyIn'},
 d:'A câmera se aproxima fisicamente do assunto sobre trilhos ou carrinho.',
 u:'Aproximar emocionalmente, dar importância ao momento.',
 p:'Smooth dolly in toward the explorer\'s face',
 v:'Dolly muda a perspectiva e cria paralaxe; zoom só amplia a imagem.'},
{c:'movimento',en:'Dolly out',pt:'Travelling para trás',tk:'smooth dolly out away from the subject',x:{shot:'ms',move:'dollyOut'},
 d:'A câmera se afasta fisicamente do assunto.',
 u:'Distanciamento, solidão, final de cena.',
 p:'Slow dolly out from the explorer, leaving them small in the landscape'},
{c:'movimento',en:'Truck',pt:'Travelling lateral',tk:'lateral trucking shot moving left to right',x:{shot:'fs',move:'truck'},
 d:'A câmera desliza para os lados, paralela à cena.',
 u:'Paralaxe forte: primeiro plano passa rápido, fundo devagar. Dá profundidade.',
 p:'Lateral trucking shot moving right past the explorer, foreground grass sliding by'},
{c:'movimento',en:'Pedestal',pt:'Pedestal',tk:'pedestal up',x:{shot:'ms',move:'pedestal'},
 d:'A câmera sobe ou desce verticalmente, sem inclinar a mira.',
 u:'Revelar algo atrás de um obstáculo; mudar a altura do olhar.',
 p:'Pedestal up shot rising from the explorer\'s chest to above their head'},
{c:'movimento',en:'Crane shot',pt:'Grua',tk:'crane shot rising up and away',x:{shot:'fs',move:'crane'},
 d:'Um braço mecânico eleva a câmera em arco, combinando altura e distância.',
 u:'Grandiosidade, abertura ou encerramento épico.',
 p:'Crane shot rising up and away from the explorer to reveal the whole valley'},
{c:'movimento',en:'Zoom in',pt:'Zoom de aproximação',tk:'slow zoom in',x:{shot:'fs',move:'zoomIn'},
 d:'A lente muda a distância focal; a câmera não se move.',
 u:'Ênfase óptica, estética de documentário ou anos 70.',
 p:'Slow zoom in on the explorer, camera stays in place',
 v:'No zoom o fundo cresce junto com o personagem; no dolly in ele fica para trás.'},
{c:'movimento',en:'Zoom out',pt:'Zoom de afastamento',tk:'slow zoom out',x:{shot:'fs',move:'zoomOut'},
 d:'A distância focal diminui e o quadro abre, sem mover a câmera.',
 u:'Revelar contexto sem a sensação física de recuo.',
 p:'Slow zoom out from the explorer revealing the surrounding meadow'},
{c:'movimento',en:'Dolly zoom',pt:'Efeito vertigo',tk:'dolly zoom (vertigo effect)',x:{shot:'ms',move:'dollyZoom'},
 d:'Dolly para um lado e zoom para o outro ao mesmo tempo: o personagem mantém o tamanho e o fundo estica ou comprime.',
 u:'Choque, revelação, vertigem. Popularizado por Hitchcock em Um Corpo que Cai (1958).',
 p:'Dolly zoom on the explorer, background stretching away while the subject stays the same size'},
{c:'movimento',en:'Orbit',pt:'Órbita / arco',tk:'slow orbit around the subject',x:{shot:'ms',move:'orbit'},
 d:'A câmera circula ao redor do personagem mantendo-o no centro. Também chamado de arc shot.',
 u:'Momento heroico, revelação, apresentar um personagem.',
 p:'Slow 180-degree orbit around the explorer, background rotating behind them'},
{c:'movimento',en:'Tracking shot',pt:'Travelling de acompanhamento',tk:'side tracking shot following the subject',x:{shot:'fs',move:'tracking',act:'walk'},
 d:'A câmera acompanha o personagem em movimento, mantendo a mesma distância.',
 u:'Jornada, perseguição, conversa andando.',
 p:'Side tracking shot following the explorer as they walk through the meadow'},
{c:'movimento',en:'Handheld',pt:'Câmera na mão',tk:'handheld camera, subtle shake',x:{shot:'ms',move:'handheld'},
 d:'Câmera carregada no ombro ou na mão, com tremor orgânico.',
 u:'Urgência, realismo documental, nervosismo.',
 p:'Handheld camera with subtle natural shake, close on the explorer'},
{c:'movimento',en:'Steadicam',pt:'Steadicam / gimbal',tk:'smooth steadicam glide',x:{shot:'fs',move:'steadicam'},
 d:'Câmera estabilizada que flutua junto com o operador, sem trancos.',
 u:'Movimento longo e fluido, plano-sequência, sensação de sonho.',
 p:'Smooth steadicam glide toward the explorer, floating camera movement'},
{c:'movimento',en:'FPV drone shot',pt:'Drone FPV',tk:'fast FPV drone dive',x:{shot:'fs',move:'fpv'},
 d:'Drone de corrida pilotado em primeira pessoa: mergulhos, curvas inclinadas, muita velocidade.',
 u:'Adrenalina, energia, transições impossíveis.',
 p:'Fast FPV drone dive from the sky down to the explorer, banking turn, motion blur'},
{c:'movimento',en:'Drone flyover',pt:'Sobrevoo de drone',tk:'drone flyover',x:{shot:'fs',move:'drone'},
 d:'Drone voa estável e alto, deslizando sobre a paisagem.',
 u:'Geografia e grandiosidade, abertura de filme.',
 p:'Drone flyover gliding above the valley, explorer below near the house'},
{c:'movimento',en:'Whip pan',pt:'Chicote',tk:'whip pan',x:{shot:'ms',move:'whip'},
 d:'Pan tão rápido que a imagem vira um borrão de movimento.',
 u:'Energia, comédia, transição entre dois planos.',
 p:'Whip pan from the explorer to the house with heavy motion blur'},
{c:'movimento',en:'Crash zoom',pt:'Zoom brusco',tk:'sudden crash zoom',x:{shot:'fs',move:'crash'},
 d:'Zoom muito rápido sobre o personagem (snap zoom).',
 u:'Comédia, choque, ênfase de anime.',
 p:'Sudden crash zoom onto the explorer\'s surprised face'},
{c:'movimento',en:'Push-in',pt:'Aproximação lenta',tk:'slow subtle push-in',x:{shot:'mcu',move:'pushIn'},
 d:'Dolly in lento e quase imperceptível.',
 u:'Tensão crescente, introspecção, momento de decisão.',
 p:'Slow subtle push-in on the explorer as they realize something'},
{c:'movimento',en:'Pull-back reveal',pt:'Recuo revelador',tk:'pull-back reveal',x:{shot:'ms',move:'reveal'},
 d:'A câmera recua e sobe para revelar um contexto que estava fora do quadro.',
 u:'Surpresa, ironia, escala.',
 p:'Pull-back reveal from the explorer to the vast valley around them'},
{c:'movimento',en:'Barrel roll',pt:'Rotação no eixo',tk:'barrel roll camera rotation',x:{shot:'ms',move:'roll'},
 d:'A câmera gira 360° sobre o eixo da própria lente.',
 u:'Desorientação, sonho, transição estilizada.',
 p:'Barrel roll camera rotation around the lens axis, the explorer spinning in frame'},

// ───────────── LENTES & FOCO ─────────────
{c:'lente',en:'14mm ultra-wide lens',pt:'Grande-angular extrema',tk:'14mm ultra-wide lens',x:{shot:'ms',lens:{f:14}},
 d:'Campo de visão enorme. Exagera distâncias: o que está perto fica gigante, o fundo fica minúsculo.',
 u:'Imersão, espaços apertados, estranheza em rostos próximos.',
 p:'Shot on a 14mm ultra-wide lens, close to the explorer, exaggerated perspective'},
{c:'lente',en:'24mm wide lens',pt:'Grande-angular',tk:'24mm wide-angle lens',x:{shot:'ms',lens:{f:24}},
 d:'Grande-angular comum: mostra bastante cenário com distorção moderada.',
 u:'Ambientes, ação, planos gerais com profundidade.',
 p:'Shot on a 24mm wide-angle lens, the explorer with plenty of background'},
{c:'lente',en:'35mm lens',pt:'35 mm',tk:'35mm lens',x:{shot:'ms',lens:{f:35}},
 d:'A lente narrativa clássica: um pouco mais aberta que o olho humano.',
 u:'Contar história com personagem e ambiente no mesmo quadro.',
 p:'Cinematic 35mm lens, natural perspective'},
{c:'lente',en:'50mm lens',pt:'50 mm (normal)',tk:'50mm lens',x:{shot:'ms',lens:{f:50}},
 d:'Chamada de lente normal: perspectiva parecida com a do olho humano em full frame.',
 u:'Naturalidade, sem distorção chamativa.',
 p:'Shot on a 50mm lens, natural perspective, medium shot'},
{c:'lente',en:'85mm portrait lens',pt:'85 mm (retrato)',tk:'85mm portrait lens',x:{shot:'ms',lens:{f:85,N:2}},
 d:'Teleobjetiva curta. Achata levemente o rosto e isola o fundo.',
 u:'Retratos favoráveis, close-ups, fundo suave.',
 p:'85mm portrait lens, f/2, the explorer sharp against a soft background'},
{c:'lente',en:'200mm telephoto lens',pt:'Teleobjetiva',tk:'200mm telephoto lens, compressed perspective',x:{shot:'fs',lens:{f:200,N:4}},
 d:'Distância focal longa. Comprime a profundidade: o fundo parece colado no personagem.',
 u:'Observar de longe, compressão de multidões e paisagens.',
 p:'200mm telephoto lens, compressed perspective, mountains looming right behind the explorer'},
{c:'lente',en:'Macro lens',pt:'Macro',tk:'macro lens, extreme detail',x:{shot:'macro'},
 d:'Foca muito perto e reproduz objetos pequenos em tamanho real ou maior.',
 u:'Texturas, insetos, gotas, detalhes de objeto. Profundidade de campo minúscula.',
 p:'Macro lens shot of a red flower petal, extreme detail, razor-thin focus'},
{c:'lente',en:'Fisheye lens',pt:'Olho de peixe',tk:'fisheye lens distortion',x:{shot:'mcu',lens:{f:12},fx:['fisheye']},
 d:'Ultra-grande-angular com distorção curva intensa, até 180°.',
 u:'Skate, videoclipe, cômico, sonho, câmera de segurança.',
 p:'Fisheye lens close to the explorer, curved distorted horizon'},
{c:'lente',en:'Anamorphic lens',pt:'Lente anamórfica',tk:'anamorphic lens, horizontal lens flares',x:{shot:'fs',lens:{f:40},light:'night',fx:['letterbox','anaflare']},
 d:'Lente que comprime a imagem na horizontal para gravar em tela larga (2.39:1). Gera flares horizontais e bokeh oval.',
 u:'O visual "cinema de blockbuster".',
 p:'Anamorphic lens, 2.39:1 widescreen, blue horizontal lens flare from a street lamp'},
{c:'lente',g:'foco',en:'Shallow depth of field',pt:'Profundidade de campo rasa',tk:'shallow depth of field',x:{shot:'ms',lens:{f:85,N:1.4}},
 d:'Só uma fatia fina da cena fica nítida; o resto desfoca. Obtido com abertura grande (f/1.4) e lente longa.',
 u:'Isolar o personagem, guiar o olhar, visual cinematográfico.',
 p:'Shallow depth of field, f/1.4, the explorer in sharp focus, background melting into blur'},
{c:'lente',g:'foco',en:'Deep focus',pt:'Foco profundo',tk:'deep focus, everything sharp',x:{shot:'fs',lens:{f:18,N:16}},
 d:'Tudo nítido do primeiro plano ao fundo. Abertura pequena (f/11–f/16) e lente aberta.',
 u:'Várias camadas de ação ao mesmo tempo, estilo Cidadão Kane.',
 p:'Deep focus, f/16, foreground grass and distant mountains equally sharp'},
{c:'lente',g:'foco',en:'Bokeh',pt:'Bokeh',tk:'creamy bokeh',x:{shot:'cu',light:'blue',lens:{f:85,N:1.2}},
 d:'A qualidade do desfoque, principalmente das luzes pontuais, que viram discos.',
 u:'Atmosfera noturna, romance, festa.',
 p:'Creamy bokeh from string lights behind the explorer at dusk'},
{c:'lente',g:'foco',en:'Rack focus',pt:'Troca de foco',tk:'rack focus from foreground to subject',x:{shot:'ms',lens:{f:85,N:1.6},rack:true},
 d:'O foco muda de um plano para outro durante o plano.',
 u:'Direcionar a atenção, revelar algo, conectar dois elementos.',
 p:'Rack focus from a leafy branch in the foreground to the explorer behind it'},
{c:'lente',g:'foco',en:'Tilt-shift',pt:'Tilt-shift (miniatura)',tk:'tilt-shift miniature effect',x:{shot:'fs',angle:'aerial',fx:['tiltshift'],grade:'vibrant'},
 d:'A faixa de foco é inclinada: só uma tira horizontal fica nítida.',
 u:'Faz cenas reais parecerem maquetes. Ótimo com plano aéreo e cores saturadas.',
 p:'Tilt-shift miniature effect, aerial view of the valley, toy-like'},
{c:'lente',g:'atmos',en:'Lens flare',pt:'Flare de lente',tk:'lens flare',x:{shot:'fs',light:'golden',move:'flare',fx:['flare']},
 d:'Reflexos internos da lente quando uma luz forte entra no quadro: halos, círculos e raias.',
 u:'Calor, sol, nostalgia, ficção científica.',
 p:'Warm lens flare as the low sun enters the frame beside the explorer'},

// ───────────── LUZ ─────────────
{c:'luz',en:'Key light',pt:'Luz principal',tk:'strong key light from the side',x:{shot:'mcu',light:'key'},
 d:'A fonte dominante da cena. Sua direção define de que lado fica a sombra.',
 u:'Toda descrição de luz começa por ela: de onde vem e quão forte é.',
 p:'Strong key light from the left, deep shadow on the right side of the face'},
{c:'luz',en:'Fill light',pt:'Luz de preenchimento',tk:'soft fill light',x:{shot:'mcu',light:'fill'},
 d:'Luz mais fraca do lado oposto à principal, que suaviza as sombras.',
 u:'Controla o contraste. Sem fill = drama; muito fill = imagem chapada.',
 p:'Soft fill light lifting the shadows, low contrast'},
{c:'luz',en:'Rim light',pt:'Contraluz de recorte',tk:'rim light, backlit edges',x:{shot:'mcu',light:'rim'},
 d:'Luz atrás do personagem que desenha um contorno brilhante nas bordas.',
 u:'Separar o personagem do fundo escuro. Muito usado em animação 3D.',
 p:'Rim light outlining the explorer\'s silhouette against a dark background'},
{c:'luz',en:'Three-point lighting',pt:'Iluminação de três pontos',tk:'three-point lighting',x:{shot:'mcu',light:'three'},
 d:'Esquema padrão: key (principal) + fill (preenchimento) + back/rim (recorte).',
 u:'Ponto de partida de estúdio para retratos limpos e controlados.',
 p:'Classic three-point lighting, key from left, soft fill, warm rim light'},
{c:'luz',en:'High-key lighting',pt:'Luz high-key',tk:'bright high-key lighting',x:{shot:'fs',light:'highkey'},
 d:'Imagem clara, sombras mínimas, baixo contraste.',
 u:'Comédia, publicidade, infantil, leveza.',
 p:'Bright high-key lighting, airy, minimal shadows'},
{c:'luz',en:'Low-key lighting',pt:'Luz low-key',tk:'moody low-key lighting',x:{shot:'ms',light:'lowkey'},
 d:'Predomínio de sombras, uma fonte forte, alto contraste.',
 u:'Suspense, noir, terror, drama.',
 p:'Moody low-key lighting, single source, most of the frame in shadow'},
{c:'luz',en:'Hard light',pt:'Luz dura',tk:'hard light, crisp shadows',x:{shot:'fs',light:'hard'},
 d:'Fonte pequena e direta (sol do meio-dia, spot). Sombras com borda nítida.',
 u:'Calor, tensão, verão, textura acentuada.',
 p:'Hard midday sunlight, crisp defined shadows on the grass'},
{c:'luz',en:'Soft light',pt:'Luz suave',tk:'soft diffused light',x:{shot:'fs',light:'soft'},
 d:'Fonte grande ou difusa (céu nublado, softbox). Sombras com transição gradual.',
 u:'Delicadeza, beleza, calma.',
 p:'Soft diffused overcast light, gentle shadows'},
{c:'luz',en:'Golden hour',pt:'Hora dourada',tk:'golden hour sunlight',x:{shot:'fs',light:'golden'},
 d:'Logo após o nascer ou antes do pôr do sol: luz baixa, quente, sombras longas.',
 u:'Nostalgia, romance, beleza natural.',
 p:'Golden hour, warm low sun, long shadows stretching across the meadow'},
{c:'luz',en:'Blue hour',pt:'Hora azul',tk:'blue hour twilight',x:{shot:'fs',light:'blue'},
 d:'Pouco antes do nascer ou logo após o pôr do sol: céu azul profundo, luzes artificiais começando a acender.',
 u:'Melancolia, calma, transição dia-noite.',
 p:'Blue hour twilight, deep blue sky, warm window lights glowing'},
{c:'luz',en:'Chiaroscuro',pt:'Claro-escuro',tk:'chiaroscuro lighting',x:{shot:'mcu',light:'chiaro'},
 d:'Contraste dramático entre luz e sombra, herdado da pintura barroca (Caravaggio, Rembrandt).',
 u:'Drama clássico, mistério, solenidade.',
 p:'Chiaroscuro lighting, half of the face in deep shadow, painterly contrast'},
{c:'luz',en:'Silhouette',pt:'Silhueta',tk:'backlit silhouette',x:{shot:'fs',angle:'low',light:'silhouette'},
 d:'Fonte forte atrás do personagem: ele vira uma forma escura contra o fundo claro.',
 u:'Mistério, iconografia, foco na pose e na forma.',
 p:'Backlit silhouette of the explorer against a blazing sunset'},
{c:'luz',en:'Volumetric lighting',pt:'Luz volumétrica',tk:'volumetric light rays',x:{shot:'fs',light:'volumetric',fx:['dust']},
 d:'Feixes de luz visíveis porque atravessam névoa, poeira ou fumaça (god rays).',
 u:'Espiritualidade, floresta mágica, catedral.',
 p:'Volumetric god rays streaming through the trees, dust particles floating'},
{c:'luz',en:'Practical lights',pt:'Luz prática',tk:'motivated practical lights',x:{shot:'fs',light:'practical'},
 d:'Fontes de luz visíveis dentro da cena (poste, janela, abajur) que justificam a iluminação.',
 u:'Realismo noturno, ambientes internos aconchegantes.',
 p:'Night scene lit only by practical lights: a street lamp and a glowing window'},
{c:'luz',en:'Neon lighting',pt:'Luz neon',tk:'neon lighting, magenta and cyan',x:{shot:'ms',light:'neon'},
 d:'Fontes coloridas saturadas, geralmente magenta e ciano, de letreiros e tubos.',
 u:'Cyberpunk, noite urbana, synthwave.',
 p:'Neon lighting, magenta rim light and cyan fill on the explorer at night'},

// ───────────── COMPOSIÇÃO ─────────────
{c:'composicao',en:'Rule of thirds',pt:'Regra dos terços',tk:'rule of thirds composition',x:{shot:'fs',comp:{thirds:true}},
 d:'O quadro é dividido em 3×3; o assunto fica sobre uma das linhas ou interseções.',
 u:'Composição equilibrada e dinâmica, deixa espaço para o cenário respirar.',
 p:'Rule of thirds composition, the explorer on the left third, open meadow to the right'},
{c:'composicao',en:'Symmetrical composition',pt:'Composição simétrica',tk:'centered symmetrical composition',x:{shot:'ws',comp:{sym:true}},
 d:'O assunto no centro exato, com o cenário espelhado dos dois lados.',
 u:'Ordem, formalidade, humor estilizado (estética de Wes Anderson).',
 p:'Perfectly centered symmetrical composition, the explorer in front of the house, trees mirrored on both sides'},
{c:'composicao',en:'Leading lines',pt:'Linhas guia',tk:'leading lines toward the subject',x:{shot:'ws',angle:'high',comp:{path:true}},
 d:'Linhas do cenário (estrada, cerca, rio) que conduzem o olhar até o assunto.',
 u:'Guiar o olhar, criar profundidade.',
 p:'A winding dirt path forming leading lines toward the explorer and the house'},
{c:'composicao',en:'Negative space',pt:'Espaço negativo',tk:'vast negative space',x:{shot:'ws',lens:{f:50},comp:{neg:true}},
 d:'Grandes áreas vazias ao redor de um assunto pequeno.',
 u:'Solidão, minimalismo, respiro para texto.',
 p:'Minimalist composition with vast negative space, tiny explorer in the lower corner, empty sky'},
{c:'composicao',en:'Frame within a frame',pt:'Moldura dentro do quadro',tk:'framed by foreground foliage',x:{shot:'fs',comp:{fgframe:true}},
 d:'Elementos do primeiro plano (galhos, portas, janelas) emolduram o assunto.',
 u:'Voyeurismo, profundidade, foco.',
 p:'The explorer framed by dark out-of-focus leaves in the foreground'},
{c:'composicao',en:'Depth layers',pt:'Camadas de profundidade',tk:'distinct foreground, midground and background',x:{shot:'ws',move:'truck',comp:{layers:true}},
 d:'Cena organizada em primeiro plano, plano médio e fundo.',
 u:'Profundidade e riqueza. Base do multiplano na animação clássica.',
 p:'Layered composition with foreground grass, the explorer in the midground, mountains in the background'},
{c:'composicao',en:'Parallax',pt:'Paralaxe',tk:'strong parallax',x:{shot:'fs',lens:{f:24},move:'truck'},
 d:'Objetos próximos se movem mais rápido que os distantes quando a câmera se desloca.',
 u:'Sensação de profundidade em 2.5D, motion graphics e multiplano.',
 p:'Lateral camera move with strong parallax between foreground grass and distant mountains'},
{c:'composicao',en:'Lead room',pt:'Espaço de direção',tk:'lead room in the direction of movement',x:{shot:'fs',act:'walk',comp:{lead:true}},
 d:'Espaço livre à frente do personagem, na direção em que ele olha ou anda.',
 u:'Sem lead room o quadro parece apertado e o movimento, travado.',
 p:'The explorer walking right with generous lead room ahead of them'},
{c:'composicao',en:'Vertical 9:16',pt:'Vertical 9:16',tk:'vertical 9:16 aspect ratio',x:{shot:'fs',comp:{aspect:'9:16'}},
 d:'Formato vertical de celular (Reels, TikTok, Shorts).',
 u:'Defina no prompt e na configuração do modelo; muitos geram em 16:9 por padrão.',
 p:'Vertical 9:16 framing, the explorer centered full body'},
{c:'composicao',en:'Widescreen 2.39:1',pt:'Tela larga 2.39:1',tk:'cinematic 2.39:1 widescreen',x:{shot:'ws',fx:['letterbox']},
 d:'Proporção de cinema anamórfico, com faixas pretas em telas 16:9.',
 u:'Visual épico e cinematográfico.',
 p:'Cinematic 2.39:1 widescreen frame of the valley'},

// ───────────── TEMPO & RITMO ─────────────
{c:'tempo',en:'Slow motion',pt:'Câmera lenta',tk:'slow motion',x:{shot:'fs',time:'slowmo',act:'hop',fx:['leaves']},
 d:'A ação acontece mais devagar que na realidade. Gravado em alta taxa (120 fps) e exibido a 24 fps.',
 u:'Ênfase, beleza, impacto, detalhe de um instante.',
 p:'Slow motion, leaves drifting as the explorer jumps'},
{c:'tempo',en:'Time-lapse',pt:'Time-lapse',tk:'time-lapse',x:{shot:'ws',time:'timelapse'},
 d:'Muito tempo comprimido em poucos segundos: nuvens correm, a luz muda.',
 u:'Passagem do tempo, ciclos, escala.',
 p:'Time-lapse of the valley from day to night, clouds racing, shadows sweeping'},
{c:'tempo',en:'Speed ramp',pt:'Rampa de velocidade',tk:'speed ramp',x:{shot:'fs',time:'ramp',act:'hop',fx:['leaves']},
 d:'A velocidade muda dentro do mesmo plano: normal, câmera lenta, normal.',
 u:'Ação estilizada, esportes, videoclipe.',
 p:'Speed ramp from real-time to slow motion at the peak of the jump'},
{c:'tempo',en:'Freeze frame',pt:'Congelamento',tk:'freeze frame',x:{shot:'fs',time:'freeze',act:'hop',fx:['leaves']},
 d:'A imagem para em um único quadro.',
 u:'Pontuação cômica, final, apresentação de personagem.',
 p:'Freeze frame mid-jump'},
{c:'tempo',en:'Reverse motion',pt:'Movimento reverso',tk:'reversed footage',x:{shot:'fs',time:'reverse',act:'hop',fx:['leaves']},
 d:'A ação roda de trás para frente.',
 u:'Estranhamento, magia, rebobinar.',
 p:'Reversed footage, leaves rising back up into the trees'},
{c:'tempo',en:'Motion blur',pt:'Desfoque de movimento',tk:'natural motion blur',x:{shot:'fs',move:'pan',mb:.7},
 d:'Rastro que objetos rápidos deixam em cada quadro por causa do tempo de exposição (obturador 180°).',
 u:'Movimento crível e cinematográfico. Sem ele, ação parece "videogame".',
 p:'Natural motion blur, 180-degree shutter'},
{c:'tempo',en:'24 fps',pt:'Taxa de quadros',tk:'24fps cinematic frame rate',x:{p2d:'fps'},
 d:'Quantos quadros por segundo. 24 fps é o padrão de cinema; 30 e 60 parecem vídeo/TV.',
 u:'24 fps dá a cadência "de filme". Mencione a taxa quando o modelo permitir.',
 p:'Cinematic 24fps look'},
{c:'tempo',en:'Animated on twos',pt:'Animação em dois',tk:'animated on twos',x:{p2d:'twos'},
 d:'Cada desenho fica na tela por 2 quadros (12 desenhos por segundo a 24 fps). On threes: 8 por segundo.',
 u:'Cadência típica de animação 2D e anime; dá textura "feita à mão".',
 p:'Hand-drawn animation on twos, slightly choppy charming timing'},
{c:'tempo',en:'Keyframes & in-betweens',pt:'Chaves e intervalos',tk:'clear keyframes and smooth in-betweens',x:{p2d:'pose'},
 d:'Keyframes são as poses principais; in-betweens (tweens) são os quadros intermediários que ligam uma pose à outra.',
 u:'Vocabulário para pedir poses claras e transições suaves.',
 p:'Strong clear key poses with smooth in-betweens'},
{c:'tempo',en:'Smear frame',pt:'Quadro de borrão',tk:'cartoon smear frames',x:{p2d:'smear'},
 d:'Um quadro desenhado propositalmente esticado ou multiplicado para sugerir velocidade extrema.',
 u:'Ação cartunesca, golpes rápidos, estilo cartoon dos anos 40.',
 p:'Fast punch with cartoon smear frames'},
{c:'tempo',en:'Seamless loop',pt:'Loop / ciclo',tk:'seamless loop',x:{p2d:'loop'},
 d:'Animação cujo último quadro emenda no primeiro. Ciclos de caminhada são o exemplo clássico.',
 u:'GIFs, fundos animados, sprites de jogos.',
 p:'Seamless looping walk cycle, side view'},
{c:'tempo',en:'Moving hold',pt:'Pausa viva',tk:'subtle moving hold',x:{p2d:'hold'},
 d:'Quando o personagem para, ainda mantém micro-movimentos (respiração, piscar). Uma pausa totalmente parada parece morta.',
 u:'Personagens parecem vivos mesmo em repouso.',
 p:'Character pauses with a subtle moving hold, breathing and blinking'},

// ───────────── 12 PRINCÍPIOS ─────────────
{c:'principios',en:'Squash and stretch',pt:'Comprimir e esticar',tk:'squash and stretch',x:{p2d:'squash'},
 d:'O corpo achata no impacto e estica na velocidade, mantendo o volume.',
 u:'Peso, elasticidade e vida. O princípio mais importante.',
 p:'Bouncy cartoon ball with exaggerated squash and stretch'},
{c:'principios',en:'Anticipation',pt:'Antecipação',tk:'clear anticipation before the action',x:{p2d:'anticipation'},
 d:'Um movimento preparatório no sentido oposto antes da ação principal (agachar antes de pular).',
 u:'Prepara o espectador e dá força à ação.',
 p:'Character crouches in anticipation before a big jump'},
{c:'principios',en:'Staging',pt:'Encenação',tk:'clear staging',x:{p2d:'staging'},
 d:'Apresentar uma ideia por vez de forma inequívoca: pose, luz e enquadramento a serviço do ponto principal.',
 u:'Clareza. O espectador sabe para onde olhar.',
 p:'Clear staging, the main character isolated in the spotlight, background simplified'},
{c:'principios',en:'Pose to pose',pt:'Pose a pose',tk:'pose-to-pose animation',x:{p2d:'pose'},
 d:'Planeja as poses-chave primeiro e preenche depois. O oposto é straight ahead (desenhar quadro a quadro em sequência).',
 u:'Pose to pose: controle e clareza. Straight ahead: fogo, água, caos orgânico.',
 p:'Pose-to-pose animation with strong silhouettes in each key pose'},
{c:'principios',en:'Follow-through',pt:'Continuidade e sobreposição',tk:'follow-through and overlapping action',x:{p2d:'follow'},
 d:'Partes soltas (cabelo, cauda, roupa) continuam se movendo depois que o corpo para, cada uma com seu atraso.',
 u:'Credibilidade física e fluidez.',
 p:'Follow-through and overlapping action, the scarf and antenna keep swinging after the character stops'},
{c:'principios',en:'Slow in and slow out',pt:'Aceleração e desaceleração',tk:'smooth ease-in and ease-out',x:{p2d:'ease'},
 d:'Mais quadros perto do início e do fim de um movimento, menos no meio. Em software: ease in / ease out.',
 u:'Movimento natural. Linear parece mecânico.',
 p:'Smooth ease-in and ease-out motion, no robotic linear movement',
 v:'Ease in = acelera ao sair; ease out = desacelera ao chegar. Os nomes variam entre softwares; descreva o efeito.'},
{c:'principios',en:'Arcs',pt:'Arcos',tk:'natural arcing motion',x:{p2d:'arcs'},
 d:'Movimentos orgânicos seguem trajetórias curvas, não linhas retas.',
 u:'Naturalidade em gestos, viradas de cabeça, objetos lançados.',
 p:'Natural arcing motion as the character turns their head'},
{c:'principios',en:'Secondary action',pt:'Ação secundária',tk:'subtle secondary action',x:{p2d:'secondary'},
 d:'Uma ação menor que acompanha e reforça a principal (assobiar enquanto anda).',
 u:'Personalidade e riqueza sem roubar o foco.',
 p:'The character walks while whistling, scarf fluttering as secondary action'},
{c:'principios',en:'Timing',pt:'Timing',tk:'snappy timing',x:{p2d:'timing'},
 d:'Quantos quadros uma ação dura. Poucos quadros = rápido e leve; muitos = lento e pesado.',
 u:'Define peso, humor e emoção.',
 p:'Snappy cartoon timing, quick fast actions with held poses'},
{c:'principios',en:'Exaggeration',pt:'Exagero',tk:'exaggerated cartoony motion',x:{p2d:'exag'},
 d:'Ampliar poses, expressões e movimentos além do realista para comunicar melhor.',
 u:'Cartoon, comédia, clareza de emoção.',
 p:'Exaggerated cartoony motion and expressions'},
{c:'principios',en:'Solid drawing',pt:'Desenho sólido',tk:'solid volumetric forms',x:{p2d:'solid'},
 d:'Formas com volume, peso e perspectiva consistentes em 3D, mesmo em 2D.',
 u:'Evita personagens "achatados" ou que mudam de forma (morphing).',
 p:'Solid volumetric character design, consistent proportions in every frame'},
{c:'principios',en:'Appeal',pt:'Apelo',tk:'appealing character design',x:{p2d:'appeal'},
 d:'Carisma do design: silhueta clara, formas variadas, proporções agradáveis.',
 u:'O público quer olhar para o personagem, herói ou vilão.',
 p:'Appealing character design, big expressive eyes, clear readable silhouette'},

// ───────────── ESTILOS ─────────────
{c:'estilo',en:'Voxel art',pt:'Arte em voxels',tk:'voxel art style, blocky 3D world',x:{shot:'ws',angle:'high',move:'orbit',style:'voxel'},
 d:'Mundo e personagens construídos com cubos (voxels), como pixels em 3D, com texturas em pixel art.',
 u:'Jogos de blocos, dioramas, nostalgia. Descreva como "voxel" ou "blocky": nomes de jogos podem ser bloqueados ou puxar personagens de terceiros.',
 p:'Voxel art style, blocky 3D world, a small explorer in a red scarf on a grassy hill, soft shadows, ambient occlusion'},
{c:'estilo',en:'Hand-drawn 2D animation',pt:'Animação 2D tradicional',tk:'hand-drawn 2D animation',x:{shot:'fs',style:'hand'},
 d:'Desenhado à mão quadro a quadro, com linhas que "fervem" levemente (line boil).',
 u:'Calor artesanal, clássicos da Disney e animação autoral.',
 p:'Traditional hand-drawn 2D animation, visible pencil lines, subtle line boil, painted backgrounds'},
{c:'estilo',en:'Anime style',pt:'Estilo anime',tk:'anime style, cel shading, vibrant sky',x:{shot:'fs',style:'anime',light:'day'},
 d:'Linguagem japonesa: contornos limpos, sombras em blocos, céus saturados, olhos expressivos.',
 u:'Descreva os traços visuais em vez de citar estúdios: é mais portátil entre modelos.',
 p:'Anime style, clean line art, cel-shaded, vivid blue sky with towering clouds'},
{c:'estilo',en:'3D CGI animation',pt:'Animação 3D',tk:'3D animated feature film style, soft global illumination',x:{shot:'fs',style:'cgi'},
 d:'Modelos 3D renderizados com luz suave, materiais realistas e profundidade de campo.',
 u:'Visual de longa de estúdio 3D.',
 p:'3D animated feature film style, soft global illumination, subsurface scattering on skin'},
{c:'estilo',en:'Stop-motion',pt:'Stop-motion',tk:'stop-motion animation',x:{shot:'fs',style:'stop',act:'hop'},
 d:'Objetos físicos fotografados quadro a quadro. Pequenos tremores entre quadros e cadência de 12 fps.',
 u:'Charme artesanal, tatilidade.',
 p:'Stop-motion animation, handcrafted miniature set, slightly jittery 12fps movement'},
{c:'estilo',en:'Claymation',pt:'Massinha',tk:'claymation, plasticine texture',x:{shot:'fs',style:'clay',act:'hop'},
 d:'Stop-motion com bonecos de massinha: formas arredondadas e marcas de dedo.',
 u:'Humor, infantil, Aardman.',
 p:'Claymation, plasticine characters with visible fingerprints, soft studio lighting'},
{c:'estilo',en:'Paper cutout',pt:'Recorte de papel',tk:'paper cutout animation',x:{shot:'fs',style:'cutout'},
 d:'Camadas de papel recortado com sombras projetadas entre elas.',
 u:'Livro infantil, teatro de sombras, motion design artesanal.',
 p:'Paper cutout animation, layered textured paper with soft drop shadows'},
{c:'estilo',en:'Pixel art',pt:'Pixel art',tk:'pixel art, 16-bit',x:{shot:'ws',style:'pixel'},
 d:'Imagem construída com pixels grandes e paleta limitada, herança dos videogames 8/16-bit.',
 u:'Retrô, games, nostalgia.',
 p:'16-bit pixel art scene, limited palette, crisp pixels'},
{c:'estilo',en:'Cel-shaded',pt:'Cel shading (toon)',tk:'cel-shaded 3D, bold outlines',x:{shot:'fs',style:'cel',light:'hard'},
 d:'3D renderizado para parecer 2D: sombras chapadas em degraus e contorno preto.',
 u:'Games estilizados, Aranhaverso, anime 3D.',
 p:'Cel-shaded 3D, flat two-tone shading, bold black outlines'},
{c:'estilo',en:'Watercolor',pt:'Aquarela',tk:'watercolor painting style',x:{shot:'ws',style:'water'},
 d:'Manchas transparentes, bordas suaves, textura de papel granulado.',
 u:'Poesia, infância, contemplação.',
 p:'Watercolor painting style, soft bleeding edges, textured cold-press paper'},
{c:'estilo',en:'Film noir',pt:'Noir',tk:'film noir, black and white',x:{shot:'ms',style:'noir',light:'hard'},
 d:'Preto e branco de alto contraste, sombras duras e atmosfera de mistério.',
 u:'Policial, mistério, anos 40.',
 p:'Film noir, high-contrast black and white, hard shadows'},
{c:'estilo',en:'Isometric',pt:'Isométrico',tk:'isometric view, orthographic',x:{shot:'ws',style:'iso'},
 d:'Vista em diagonal sem perspectiva: linhas paralelas continuam paralelas.',
 u:'Diorama, jogos de estratégia, infográficos.',
 p:'Isometric diorama of the valley, orthographic camera, clean geometry'},

// ───────────── COR & ACABAMENTO ─────────────
{c:'cor',en:'Color grading',pt:'Correção/grade de cor',tk:'cinematic color grading',x:{shot:'fs',grade:'cycle'},
 d:'Ajuste artístico de cor e contraste na pós-produção. A mesma cena muda de emoção com a grade.',
 u:'Defina a paleta junto com a luz para controlar o clima.',
 p:'Cinematic color grading with a cohesive palette'},
{c:'cor',en:'Teal and orange',pt:'Teal & orange',tk:'teal and orange color grade',x:{shot:'ms',grade:'teal'},
 d:'Sombras puxadas para azul-petróleo e pele/realces para laranja. Contraste complementar.',
 u:'Blockbuster, ação.',
 p:'Teal and orange color grade, warm skin tones against cool shadows'},
{c:'cor',en:'Desaturated',pt:'Dessaturado',tk:'muted desaturated palette',x:{shot:'fs',grade:'desat'},
 d:'Cores lavadas, menos saturação.',
 u:'Melancolia, guerra, realismo frio.',
 p:'Muted desaturated palette, overcast mood'},
{c:'cor',en:'Black and white',pt:'Preto e branco',tk:'black and white',x:{shot:'fs',grade:'bw'},
 d:'Sem cor; o contraste e a forma carregam a imagem.',
 u:'Atemporalidade, memória, foco na luz.',
 p:'Black and white, rich tonal range'},
{c:'cor',en:'Vibrant colors',pt:'Cores vibrantes',tk:'vibrant saturated colors',x:{shot:'fs',grade:'vibrant'},
 d:'Saturação alta, cores puras.',
 u:'Alegria, infantil, pop.',
 p:'Vibrant saturated colors, playful'},
{c:'cor',en:'Pastel palette',pt:'Paleta pastel',tk:'soft pastel palette',x:{shot:'fs',grade:'pastel'},
 d:'Tons claros e suaves, pouco contraste.',
 u:'Delicadeza, sonho, fofura.',
 p:'Soft pastel palette, dreamy and gentle'},
{c:'cor',en:'Warm tones',pt:'Tons quentes',tk:'warm color temperature',x:{shot:'fs',grade:'warm'},
 d:'Balanço de branco puxado para amarelo/laranja.',
 u:'Aconchego, nostalgia, verão.',
 p:'Warm color temperature, cozy amber tones'},
{c:'cor',en:'Cool tones',pt:'Tons frios',tk:'cool color temperature',x:{shot:'fs',grade:'cool'},
 d:'Balanço de branco puxado para azul.',
 u:'Isolamento, tecnologia, inverno, tristeza.',
 p:'Cool color temperature, icy blue tones'},
{c:'cor',en:'Film grain',pt:'Granulação de filme',tk:'subtle film grain',x:{shot:'ms',fx:['grain']},
 d:'Textura de ruído dos cristais de prata da película.',
 u:'Organicidade; tira o aspecto plástico de imagem gerada.',
 p:'Subtle 35mm film grain'},
{c:'cor',en:'Vignette',pt:'Vinheta',tk:'soft vignette',x:{shot:'ms',fx:['vignette']},
 d:'Escurecimento gradual nas bordas do quadro.',
 u:'Concentra o olhar no centro; ar de época.',
 p:'Soft dark vignette around the edges'},
{c:'cor',en:'Halation',pt:'Halação / bloom',tk:'soft halation glow on highlights',x:{shot:'fs',light:'golden',fx:['halation']},
 d:'Brilho difuso, geralmente avermelhado, ao redor das áreas claras. Típico de película.',
 u:'Sonho, nostalgia, luz que "vaza".',
 p:'Soft halation glow around the highlights'},
{c:'cor',en:'Chromatic aberration',pt:'Aberração cromática',tk:'chromatic aberration',x:{shot:'ms',fx:['ca']},
 d:'Franjas coloridas (vermelho/azul) nas bordas de alto contraste, causadas pela lente.',
 u:'Glitch, lente vintage, desorientação.',
 p:'Slight chromatic aberration at the frame edges'},
{c:'cor',en:'35mm film look',pt:'Visual de película 35 mm',tk:'shot on 35mm film',x:{shot:'fs',grade:'film',fx:['grain','halation','vignette']},
 d:'Combinação de grão, halação, pretos levemente lavados e cor quente de película.',
 u:'Atalho poderoso: "shot on 35mm film" puxa vários traços de uma vez.',
 p:'Shot on 35mm film, Kodak Portra colors, natural grain, soft halation'},

// ───────────── ATMOSFERA ─────────────
{c:'atmos',en:'Fog',pt:'Névoa / neblina',tk:'thick rolling fog',x:{shot:'ws',fx:['fog'],light:'soft'},
 d:'Partículas de água em suspensão que apagam o fundo.',
 u:'Mistério, isolamento, profundidade.',
 p:'Thick rolling fog swallowing the trees behind the explorer'},
{c:'atmos',en:'Atmospheric perspective',pt:'Perspectiva atmosférica',tk:'atmospheric haze, receding mountains',x:{shot:'ws',lens:{f:50},fx:['haze']},
 d:'Quanto mais longe, mais claro, azulado e sem contraste. O ar entre câmera e objeto atua como filtro.',
 u:'Profundidade em paisagens; técnica de pintores de fundo.',
 p:'Layers of mountains fading into blue atmospheric haze'},
{c:'atmos',en:'Rain',pt:'Chuva',tk:'heavy rain',x:{shot:'fs',fx:['rain'],light:'soft'},
 d:'Gotas em queda, superfícies molhadas, céu fechado.',
 u:'Tristeza, limpeza, drama, romance.',
 p:'Heavy rain falling around the explorer, overcast sky'},
{c:'atmos',en:'Snowfall',pt:'Neve',tk:'gentle snowfall',x:{shot:'fs',fx:['snow'],grade:'cool'},
 d:'Flocos caindo lentamente em várias profundidades.',
 u:'Silêncio, magia, inverno.',
 p:'Gentle snowfall, large soft flakes drifting'},
{c:'atmos',en:'Floating dust',pt:'Poeira no ar',tk:'floating dust particles in the light',x:{shot:'mcu',light:'volumetric',fx:['dust']},
 d:'Partículas iluminadas flutuando no ar.',
 u:'Textura de luz, nostalgia, sótão, floresta mágica.',
 p:'Dust particles floating in a beam of sunlight'},

// ───────────── TRANSIÇÕES ─────────────
{c:'edicao',en:'Hard cut',pt:'Corte seco',tk:'hard cut',x:{trans:'cut'},
 d:'Troca instantânea de um plano para outro.',
 u:'A transição padrão; invisível quando bem feita.',
 p:'Hard cut to a wide shot of the valley'},
{c:'edicao',en:'Match cut',pt:'Corte por semelhança',tk:'match cut',x:{trans:'match'},
 d:'Corte entre dois planos ligados por forma, movimento ou posição parecidos.',
 u:'Elipses de tempo elegantes (o osso que vira nave em 2001).',
 p:'Match cut from the setting sun to the rising moon in the same position'},
{c:'edicao',en:'Jump cut',pt:'Jump cut',tk:'jump cuts',x:{trans:'jump'},
 d:'Corte dentro do mesmo enquadramento que pula no tempo; o personagem "salta" de lugar.',
 u:'Impaciência, passagem de tempo, vlog, Nouvelle Vague.',
 p:'Series of jump cuts as the explorer fidgets while waiting'},
{c:'edicao',en:'Cross dissolve',pt:'Fusão',tk:'slow cross dissolve',x:{trans:'dissolve'},
 d:'Uma imagem desaparece enquanto a outra surge por cima.',
 u:'Passagem de tempo suave, memória, sonho.',
 p:'Slow cross dissolve from day to golden hour'},
{c:'edicao',en:'Fade to black',pt:'Fade para preto',tk:'fade to black',x:{trans:'fade'},
 d:'A imagem escurece até o preto, e a próxima surge do preto.',
 u:'Fim de capítulo, pausa, morte, encerramento.',
 p:'Fade to black, then fade in on the next scene'},
{c:'edicao',en:'Wipe',pt:'Cortina',tk:'wipe transition',x:{trans:'wipe'},
 d:'Uma linha atravessa a tela trocando um plano pelo outro.',
 u:'Tom de aventura e seriado (Star Wars).',
 p:'Horizontal wipe transition to the next scene'},
{c:'edicao',en:'Iris transition',pt:'Íris',tk:'iris out',x:{trans:'iris'},
 d:'Um círculo fecha sobre a imagem até o preto, ou abre a partir dele.',
 u:'Cartoon clássico, cinema mudo, humor.',
 p:'Classic cartoon iris out closing on the explorer'},
{c:'edicao',en:'Whip pan transition',pt:'Transição em chicote',tk:'whip pan transition',x:{trans:'whip'},
 d:'Um whip pan borrado esconde o corte entre dois planos.',
 u:'Energia, vídeo de viagem, ação.',
 p:'Whip pan transition into the next location'},
{c:'edicao',en:'Smash cut',pt:'Smash cut',tk:'smash cut',x:{trans:'smash'},
 d:'Corte abrupto entre dois momentos de energia oposta (barulho → silêncio).',
 u:'Choque, comédia, despertar de pesadelo.',
 p:'Smash cut from chaos to a silent still night'},
{c:'edicao',en:'Morph transition',pt:'Transição de morph',tk:'seamless morph transition',x:{trans:'morph'},
 d:'Uma imagem se deforma até virar a outra.',
 u:'Transformação, magia. Vídeos de IA fazem isso naturalmente; peça só quando quiser.',
 p:'Seamless morph transition from day to night'},
{c:'edicao',en:'Long take',pt:'Plano-sequência',tk:'one continuous long take, no cuts',x:{trans:'long'},
 d:'Uma cena inteira em um único plano contínuo, sem cortes.',
 u:'Imersão, virtuosismo, tempo real.',
 p:'One continuous long take with no cuts, the camera gliding from the valley to the explorer\'s face'},
{c:'edicao',en:'Montage',pt:'Montagem',tk:'fast-paced montage',x:{trans:'montage'},
 d:'Sequência de planos curtos que resume tempo ou ideia.',
 u:'Treino, viagem, passagem de tempo.',
 p:'Fast-paced montage of the explorer\'s journey: close-ups, wide shots, details'}
];
